### ISSUE TITLE
Does not run on my Win7 env...

### ISSUE THREAD

**Issue by vijaycd** [martin-gorner/tensorflow-mnist-tutorial#35]
Installation went fine until I ran this .py file:  python mnist_1.0_softmax.py

```
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting data\train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting data\train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting data\t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting data\t10k-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "mnist_1.0_softmax.py", line 78, in <module>
    I = tensorflowvisu.tf_format_mnist_images(X, Y, Y_)  # assembles 10x10 images by default
  File "D:\ProgramData\tensorflow-mnist-tutorial\tensorflowvisu.py", line 42, in tf_format_mnist_images
    everything_incorrect_first = tf.concat([incorrectly_recognised_indices, correctly_recognised_indices], 0) # images reordered with indeces of unrecognised images first
  File "D:\ProgramData\Miniconda3\envs\carnd-term1\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1075, in concat
    dtype=dtypes.int32).get_shape(
  File "D:\ProgramData\Miniconda3\envs\carnd-term1\lib\site-packages\tensorflow\python\framework\ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "D:\ProgramData\Miniconda3\envs\carnd-term1\lib\site-packages\tensorflow\python\framework\constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "D:\ProgramData\Miniconda3\envs\carnd-term1\lib\site-packages\tensorflow\python\framework\constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "D:\ProgramData\Miniconda3\envs\carnd-term1\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "D:\ProgramData\Miniconda3\envs\carnd-term1\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
```
What am I missing? Thanks.

**Comment by martin-gorner** [comment]
This looks like a Tensorflow 1.0 inconsistency. Make sure you have the latest version of the code and that you are running it using the latest version of Tensorflow.

When TF reached 1.0, some breaking changes were made to clean up some APIs. I have updated the code accordingly. The messages above seem to indicate that there is a mismatch between your version of the code and your version of Tensorflow.

**Comment by martin-gorner** [comment]
closing without further updates
